add helm plugin to generate snapshot
meshery/helm-kanvas-snapshot pull request #25
Opened 2024-09-26 12:50 UTC by Aijeyomah

**Description**

This PR fixes #11431

**Notes for Reviewers**
- Add Helm plugin to generate Kanvas snaphot from helm chart

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

2024-09-26 14:41 UTC, leecalcote commented
Regarding three. Don’t do this. That’s not Paul get up for status. I’m not convinced that we should be supporting a non-email based flow.

Our time spent on trying to figure out how to let people know when the snapshot will be ready is time wasted when they can simply provide an email.

2024-09-26 14:42 UTC, leecalcote commented
@Aijeyomah please fix the eslint configuration in this repo/build workflow

2024-09-27 16:37 UTC, pontusringblom commented
@Aijeyomah, how can I try this command?

2024-09-27 16:38 UTC, pontusringblom commented on .github/workflows/build-and-release-snapshot-plugin.yml
> +      - 'v*'
Maybe it's better to just trigger on the release event...

2024-09-27 16:39 UTC, pontusringblom commented on .github/workflows/build-and-release-snapshot-plugin.yml
> +        uses: actions/setup-go@v4
```suggestion
        uses: actions/setup-go@v5
```
There is a later version..

2024-09-27 16:40 UTC, jameshorton2337 requested changes

2024-09-27 16:40 UTC, jameshorton2337 commented on .goreleaser.yaml
> +scoops:
I think this portion can be removed. Is this project releasing a Scoop package?

2024-09-27 16:41 UTC, leecalcote commented on .goreleaser.yaml
> +scoops:
You're right. Likely, we would need another repo to host that out of and, no, a scoop or chocately package isn't planned.

2024-09-27 16:42 UTC, leecalcote commented on .goreleaser.yaml
> +
```suggestion
```

Removing Scoop package

2024-09-27 16:42 UTC, jameshorton2337 commented on .goreleaser.yaml
> +    description: "Kanvase napshot plugin for Helm charts."
```suggestion
    description: "Kanvas snapshot plugin for Helm charts."
```

2024-09-30 02:46 UTC, leecalcote commented on .github/workflows/build-and-release-snapshot-plugin.yml
> +    runs-on: macos-latest
Any reason that we're using macos? I wonder how many build minutes are offered on this OS.

2024-09-30 02:49 UTC, leecalcote commented on .github/workflows/build-and-release-snapshot-plugin.yml
> +    runs-on: macos-latest
Use of macos uses 10x more minutes than a linux OS. I'm not sure if there is any limit to our build minute limit in public repo, though, so this might not matter. I'm not sure.

2024-09-30 02:55 UTC, leecalcote commented on README.md
> +- Go
```suggestion
```
Golang insn't necessary for installation, only for building, right?

2024-09-30 03:15 UTC, merged

2024-09-30 15:24 UTC, MUzairS15 commented
@Aijeyomah I see the Terminal logger from meshkit is being redefined. Any specific reason? I pushed commits to organize the code, did those got lost while resolving the conflicts?

2024-09-30 23:26 UTC, leecalcote commented
@Aijeyomah is this still in process of being resolved or has this been addressed?

2024-10-01 01:07 UTC, Aijeyomah commented
> @Aijeyomah I see the Terminal logger from meshkit is being redefined. Any specific reason? I pushed commits to organize the code, did those got lost while resolving the conflicts?
> 
> 

The logger file was empty when I pulled the changes from master, so I added those there. Maybe it occurred while fixing conflicts

2024-10-01 01:07 UTC, Aijeyomah commented
> @Aijeyomah is this still in process of being resolved or has this been addressed?

It's in the process